// Preload script for Electron context bridge

const { ipcRenderer, contextBridge } = require('electron');

// Expose necessary methods to the renderer process (the web page)
contextBridge.exposeInMainWorld('electronAPI', {
    startTranscription: () => ipcRenderer.send('start-audio-capture'),
    stopTranscription: () => ipcRenderer.send('stop-audio-capture'),
    togglePauseCapture: () => ipcRenderer.invoke('toggle-pause-capture'),
    resetSession: () => ipcRenderer.send('reset-session'),
    startAudioLevelTest: () => ipcRenderer.send('start-audio-level-test'),
    stopAudioLevelTest: () => ipcRenderer.send('stop-audio-level-test'),
    requestSuggestion: (payload) => ipcRenderer.invoke('request-suggestion', payload),
    saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
    loadSettings: () => ipcRenderer.invoke('load-settings'),
    getTierStatus: () => ipcRenderer.invoke('get-tier-status'),
    listKnowledge: (filters) => ipcRenderer.invoke('list-knowledge', filters),
      ingestKnowledgeFile: (filePath) => ipcRenderer.invoke('ingest-knowledge-file', filePath),
      uploadKnowledgeToPinecone: (id) => ipcRenderer.invoke('upload-knowledge-to-pinecone', id),
      deleteKnowledgeItem: (id) => ipcRenderer.invoke('delete-knowledge-item', id),
    setPinnedKnowledge: (ids) => ipcRenderer.invoke('set-pinned-knowledge', ids),
    getPinnedKnowledge: () => ipcRenderer.invoke('get-pinned-knowledge'),
    openKnowledgeFileDialog: () => ipcRenderer.invoke('open-knowledge-file-dialog'),
    listAudioDevices: () => ipcRenderer.invoke('list-audio-devices'),
    setAudioDevices: (devices) => ipcRenderer.invoke('set-audio-devices', devices),
    getCompanies: () => ipcRenderer.invoke('get-companies'),
    getRoles: () => ipcRenderer.invoke('get-roles'),
    getInterviews: (company) => ipcRenderer.invoke('get-interviews', company),
    deleteCompany: (company) => ipcRenderer.invoke('delete-company', company),
    renameCompany: (oldName, newName) => ipcRenderer.invoke('rename-company', oldName, newName),
    setCompanyRole: (companyName, role) => ipcRenderer.invoke('set-company-role', companyName, role),
    getCompanyJobDescription: (companyName) => ipcRenderer.invoke('get-company-jd', companyName),
    setCompanyJobDescription: (companyName, jd) => ipcRenderer.invoke('set-company-jd', companyName, jd),
    deleteInterview: (company, id) => ipcRenderer.invoke('delete-interview', company, id),
    saveInterview: (metadata) => ipcRenderer.invoke('save-interview', metadata),
    saveManualInterview: (metadata) => ipcRenderer.invoke('save-manual-interview', metadata),
    getSessions: (filters) => ipcRenderer.invoke('get-sessions', filters),
    getSessionEntities: (mode) => ipcRenderer.invoke('get-session-entities', mode),
    getOutcomeCalibrationSummary: (entity) => ipcRenderer.invoke('get-outcome-calibration-summary', entity),
    saveSession: (sessionRecord) => ipcRenderer.invoke('save-session', sessionRecord),
    deleteSession: (payload) => ipcRenderer.invoke('delete-session', payload),
    deleteSessionEntity: (payload) => ipcRenderer.invoke('delete-session-entity', payload),
    updateSessionEntity: (payload) => ipcRenderer.invoke('update-session-entity', payload),
    getTrendAnalysis: (companyId) => ipcRenderer.invoke('get-trend-analysis', companyId),
    generateTrendAnalysis: (companyId, options) => ipcRenderer.invoke('generate-trend-analysis', companyId, options),
    setActiveSessionContext: (context) => ipcRenderer.invoke('set-active-session-context', context),
    validateServices: (settings) => ipcRenderer.invoke('validate-services', settings),
    extractJobContext: (jobDescription) => ipcRenderer.invoke('extract-job-context', jobDescription),
    closeApp: () => ipcRenderer.invoke('close-app'),
    minimizeAppWindow: () => ipcRenderer.invoke('minimize-app-window'),
    maximizeAppWindow: () => ipcRenderer.invoke('maximize-app-window'),
    hideApp: () => ipcRenderer.invoke('hide-app'),
    showApp: () => ipcRenderer.invoke('show-app'),
    getAppWindowBounds: () => ipcRenderer.invoke('get-app-window-bounds'),
    moveAppWindow: (bounds) => ipcRenderer.invoke('move-app-window', bounds),
    resizeActiveCaptureWindow: (bounds) => ipcRenderer.invoke('resize-active-capture-window', bounds),
    getActiveCaptureWindowBounds: () => ipcRenderer.invoke('get-active-capture-window-bounds'),
    moveActiveCaptureWindow: (bounds) => ipcRenderer.invoke('move-active-capture-window', bounds),
    onTranscriptUpdate: (callback) => ipcRenderer.on('transcript-update', callback),
    onAssistantUpdate: (callback) => ipcRenderer.on('assistant-update', callback),
    onHealthUpdate: (callback) => ipcRenderer.on('health-update', callback),
    onAudioLevelUpdate: (callback) => ipcRenderer.on('audio-level-update', callback),
    onSessionReset: (callback) => ipcRenderer.on('session-reset', callback),
    onAudioStatus: (callback) => ipcRenderer.on('audio-status', callback),
    onSessionDataChanged: (callback) => {
        ipcRenderer.on('session-data-changed', callback);
        return () => ipcRenderer.off('session-data-changed', callback);
    }
});
